### ISSUE TITLE
Missing installation of npm

### ISSUE THREAD

**Issue by matthijsmelissen** [Ircama/osm-carto-tutorials#2]
Thanks for working on this!

At the page "Installing Kosmtik and OpenStreetMap-Carto on Ubuntu" you're using npm without installing it, so I think you need to add 'sudo apt install npm' somewhere.

**Comment by Ircama** [comment]
Thanks a lot for your comment, I had deleted it because I was considering it was already part of nodejs,

I think you are right and I should correct the installation line this way:

`sudo apt-get install nodejs npm`

I am going to repeat again the intallation on another Ubuntu system anyway, I'll double check everything.
